### ISSUE TITLE
Can update this plugin to support Redmine 3.0+

### ISSUE THREAD

**Issue by dreampet** [colszowka/redmine_commit_issue_links#1]

**Comment by colszowka** [comment]
@dreampet Sorry, but this plugin is extremely old. I also haven't been using Redmine myself in many years and therefore have no interest to update it to work with the latest versions. Even the installation mechanism (using script/plugin instead of rubygems) is from long gone times of the ruby/rails ecosystem, so a major overhaul of the whole thing would be needed. 

I would suggest you build your own from scratch using whatever Redmine recommends for plugin authoring nowadays. You surely could use the existing code in https://github.com/colszowka/redmine_commit_issue_links/blob/master/lib/redmine_commit_issue_links.rb as a starting point, but probably instead of monkey patching a module, you should look for what lifecycle hooks redmine offers to plugin authors instead.

Also, if you create a new extension that replaces this please ping me so I can add a link to the readme here for future visitors!
